# Generated by Django 4.1.7 on 2024-11-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "月"),
                            ("Tuesday", "火"),
                            ("Wednesday", "水"),
                            ("Thursday", "木"),
                            ("Friday", "金"),
                            ("Saturday", "土"),
                            ("Sunday", "日"),
                        ],
                        max_length=10,
                    ),
                ),
                ("activity", models.CharField(max_length=100)),
            ],
        ),
    ]
